# Generated by Django 5.0 on 2024-01-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CaategoryName', models.CharField(max_length=30)),
                ('task', models.ManyToManyField(to='tasks.taskmodel')),
            ],
        ),
    ]
